name: local_deps
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
dependencies: 
  mason_logger: ^0.1.0-dev.8
  pubspec_lock: ^3.0.1
  pubspec_parse: ^1.2.0
  yaml: ^3.1.0

executables:
  local_deps: